name: flutter_e_siyaha
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dropdown_button2: ^1.6.2
  firebase_auth: ^3.3.20
  flutter:
    sdk: flutter
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  flutter_maps: ^0.1.0
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^1.1.0
  fluttertoast: ^8.0.9
  google_api_headers: ^1.1.1
  google_directions_api: ^0.9.1
  google_maps_flutter: ^2.1.6
  google_maps_webservice: ^0.0.20-nullsafety.5
  places_service: ^0.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/SVGS/
    - assets/images/

  uses-material-design: true

  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend/Lexend-Thin.ttf
        - asset: fonts/Lexend/Lexend-Regular.ttf
        - asset: fonts/Lexend/Lexend-Bold.ttf
        - asset: fonts/Lexend/Lexend-Black.ttf
    - family: Roxborough
      fonts:
        - asset: fonts/Roxborough/RoxboroughCF-Bold.otf
        - asset: fonts/Roxborough/RoxboroughCF-DemiBold.otf
        - asset: fonts/Roxborough/RoxboroughCF-Heavy.otf
        - asset: fonts/Roxborough/RoxboroughCF-Medium.otf
